# Generated by Django 5.2.1 on 2025-05-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("param1", models.FloatField(default=1.0)),
                ("param2", models.IntegerField(default=0)),
                ("param3", models.IntegerField(default=50)),
                ("param4", models.BooleanField(default=False)),
                ("param5", models.BooleanField(default=False)),
                ("gpt_prompt", models.TextField(blank=True)),
                ("gpt_response", models.TextField(blank=True)),
                ("status", models.CharField(default="created", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orsaas_core.snapshot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="snapshot",
            name="linked_upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orsaas_core.upload"
            ),
        ),
    ]
