# Generated by Django 5.2.1 on 2025-05-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("param1", models.FloatField()),
                ("param2", models.IntegerField()),
                ("param3", models.IntegerField()),
                ("param4", models.BooleanField()),
                ("param5", models.BooleanField()),
                ("gpt_prompt", models.TextField(blank=True, null=True)),
                ("gpt_response", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.snapshot"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="snapshot",
            name="linked_upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.upload"
            ),
        ),
    ]
