# Generated by Django 5.2.1 on 2025-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
