# Generated by Django 5.2.1 on 2025-05-22 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_snapshot_linked_upload_scenario_extra_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='snapshot',
            name='solution_status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['owner', 'created_at'], name='core_snapsh_owner_i_f4fa8a_idx'),
        ),
    ]
