# Generated by Django 5.2.1 on 2025-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="model_type",
            field=models.CharField(
                choices=[("vrp", "VRP"), ("inventory", "Inventory")],
                default="vrp",
                max_length=20,
            ),
        ),
    ]
